name: Test
on:
    schedule:
      - cron: "0 */6 * * *"
    push:
      branches: [ main ]
    workflow_dispatch:
    
env:
  API_ID: "${{ secrets.API_ID }}"
  API_HASH: "${{ secrets.API_HASH }}"
  BOT_TOKEN: "${{ secrets.BOT_TOKEN }}"
  REDIS_URI: "${{ secrets.REDIS_URI }}"
  REDIS_PASSWORD: "${{ secrets.REDIS_PASSWORD }}"
  SESSION: "${{ secrets.SESSION }}"
  LOG_CHANNEL: "${{ secrets.LOG_CHANNEL }}"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@main
         
       - uses: styfle/cancel-workflow-action@0.9.0
         name: "Cancelling duplicate workflow runs"
         with:
            all_but_latest: true
            access_token: ${{ github.token }}
       - uses: actions/setup-node@v2
         with:
            node-version: '16'
       - name: Set up Python 3.9
         uses: actions/setup-python@v2.2.2
         with:
           python-version: 3.9
       - name: cloning repo and install

         continue-on-error: true
         run: |
          #  echo "API_ID=${{ secrets.API_ID }} | tee .env
          #  echo "API_HASH=${{ secrets.API_HASH }} | tee -a .env
          #  echo "LOG_CHANNEL=${{ secrets.LOG_CHANNEL }} | tee -a .env
          #  echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} | tee -a .env
          #  echo "SESSION=${{ secrets.SESSION }} | tee -a .env
          #  echo "REDIS_URI=${{ secrets.REDIS_URI }} | tee -a .env
          #  echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }} | tee -a .env || echo "Proceeding with bot"
          #  cat .env
       - name: Running Userbot
         timeout-minutes: 350
         continue-on-error: true
         run: |
           sudo sh ultroid.sh
           echo "Bot Started"
